spring:
  application:
    name: project-core-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/.well-known/jwks.json
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:project_core_db}
    username: ${DB_USERNAME:project_core_user}
    password: ${DB_PASSWORD:project_core_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never


server:
  port: 8081
