CREATE TABLE projects
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    key         VARCHAR(10)                             NOT NULL,
    description VARCHAR(255),
    owner_id    BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE,
    updated_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT uk_projects_key UNIQUE (key)
);

CREATE TABLE project_members
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    role       VARCHAR(20)                             NOT NULL,
    joined_at  TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_project_members PRIMARY KEY (id),
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT uk_project_members_project_user UNIQUE (project_id, user_id),
    CONSTRAINT chk_project_members_role CHECK (role IN ('OWNER', 'MEMBER', 'VIEWER'))
);

CREATE INDEX idx_project_members_user_id
    ON project_members (user_id);

CREATE INDEX idx_project_members_project_id
    ON project_members (project_id);
