CREATE TABLE IF NOT EXISTS issue
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id  BIGINT                                  NOT NULL,
    type        SMALLINT                                NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    status      SMALLINT                                NOT NULL,
    priority    SMALLINT                                NOT NULL,
    assignee_id BIGINT,
    reporter_id BIGINT                                  NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_issue PRIMARY KEY (id)
);
