ALTER TABLE project_members
DROP
CONSTRAINT fk_project_members_project;

CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    issue_id   BIGINT                                  NOT NULL,
    project_id BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    body       TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE issues
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id   BIGINT                                  NOT NULL,
    issue_number BIGINT                                  NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    title        VARCHAR(255)                            NOT NULL,
    description  VARCHAR(255),
    status       VARCHAR(255)                            NOT NULL,
    priority     VARCHAR(255)                            NOT NULL,
    assignee_id  BIGINT,
    reporter_id  BIGINT                                  NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_issues PRIMARY KEY (id)
);

ALTER TABLE projects
    ADD next_issue_number BIGINT;

ALTER TABLE projects
    ALTER COLUMN next_issue_number SET NOT NULL;

ALTER TABLE issues
    ADD CONSTRAINT uk_issues_project_issue_number UNIQUE (project_id, issue_number);

DROP TABLE issue CASCADE;