CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    issue_id   BIGINT                                  NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    body       TEXT                                    NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT fk_comments_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_comments_issue FOREIGN KEY (issue_id) REFERENCES issues (id)
);

CREATE INDEX idx_comments_project_issue_created_at
    ON comments (project_id, issue_id, created_at);