CREATE TABLE boards
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    project_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_boards PRIMARY KEY (id),
    CONSTRAINT uk_boards_projects UNIQUE (project_id),
    CONSTRAINT fk_boards_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE board_columns
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    board_id   BIGINT                                  NOT NULL,
    project_id BIGINT                                  NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    position   INTEGER                                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_board_columns PRIMARY KEY (id),
    CONSTRAINT uk_board_columns_board_position UNIQUE (board_id, position),
    CONSTRAINT uk_board_columns_id_project UNIQUE (id, project_id),
    CONSTRAINT fk_board_columns_board FOREIGN KEY (board_id) REFERENCES boards (id),
    CONSTRAINT fk_board_columns_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

INSERT INTO boards (project_id, created_at, updated_at)
SELECT id, now(), now()
FROM projects;

INSERT INTO board_columns (board_id, project_id, name, position, created_at, updated_at)
SELECT b.id, b.project_id, default_columns.name, default_columns.position, now(), now()
FROM boards b
CROSS JOIN (
    VALUES
        ('To Do', 1),
        ('In Progress', 2),
        ('Done', 3),
        ('Cancelled', 4)
) AS default_columns(name, position);

ALTER TABLE issues
    ADD COLUMN column_id BIGINT,
    ADD COLUMN position INTEGER;

WITH issue_positions AS (
    SELECT
        id,
        project_id,
        status,
        row_number() OVER (PARTITION BY project_id, status ORDER BY issue_number) AS position
    FROM issues
)
UPDATE issues
SET column_id = board_columns.id,
    position = issue_positions.position
FROM issue_positions
JOIN boards
    ON boards.project_id = issue_positions.project_id
JOIN board_columns
    ON board_columns.board_id = boards.id
   AND board_columns.position = CASE issue_positions.status
        WHEN 'TODO' THEN 1
        WHEN 'IN_PROGRESS' THEN 2
        WHEN 'DONE' THEN 3
        WHEN 'CANCELLED' THEN 4
   END
WHERE issues.id = issue_positions.id;

ALTER TABLE issues
    ALTER COLUMN column_id SET NOT NULL,
    ALTER COLUMN position SET NOT NULL;

ALTER TABLE issues
    ADD CONSTRAINT fk_issues_column_project
        FOREIGN KEY (column_id, project_id) REFERENCES board_columns (id, project_id);

ALTER TABLE issues
    DROP COLUMN status;

CREATE INDEX idx_board_columns_project_id
    ON board_columns (project_id);

CREATE INDEX idx_issues_project_column_position
    ON issues (project_id, column_id, position);
